server:
  port: 8085
  servlet:
    contextPath: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/teaching-system
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 10
        order_inserts: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.vti.ufinity.teaching.management

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.vti.ufinity.teaching.management: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: vti.com.vn
  expirationMinute: 10080 # one week

swagger:
  contact-name: VTI
  contact-mail: duc.nguyenviet@vti.com.vn
  contact-url: https://vti.com.vn/
  app-name: Spring Boot Teaching System Project
  app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot, Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger"
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
